package main.java.com.pranay.code_review_platform_backend.review.detector;

import com.pranay.code_review_platform_backend.review.model.ReviewIssue;
import net.sourceforge.pmd.RuleViolation;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

@Component
public class ComplexityDetector {

    /**
     * Maps PMD rule violations into standard domain ReviewIssue objects.
     *
     * @param repositoryId Target repository ID
     * @param violations   Raw violations generated by PMD execution
     * @return List of normalized ReviewIssue entities
     */
    public List<ReviewIssue> processPmdViolations(Long repositoryId, List<RuleViolation> violations) {
        List<ReviewIssue> issues = new ArrayList<>();

        for (RuleViolation violation : violations) {
            ReviewIssue issue = new ReviewIssue(
                repositoryId,
                "COMPLEXITY",
                violation.getDescription(),
                violation.getFilename(),
                violation.getBeginLine(),
                mapPmdPriorityToSeverity(violation.getRule().getPriority().getPriority()),
                "Consider reducing nested control structures or breaking down complex conditional paths."
            );

            issues.add(issue);
        }

        return issues;
    }

    /**
     * Converts PMD priority levels (1 = highest, 5 = lowest) to internal severity standards.
     */
    private String mapPmdPriorityToSeverity(int priority) {
        return switch (priority) {
            case 1 -> "CRITICAL";
            case 2 -> "HIGH";
            case 3 -> "MEDIUM";
            default -> "LOW";
        };
    }
}