spring.application.name=code-review-platform-backend
@Value("${ai.service.url}")
private String aiServiceUrl;
ai.service.url=http://localhost:8001


server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/code_review_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.client.registration.github.client-id=Ov23li0MgC7vbXpvTPR9
spring.security.oauth2.client.registration.github.client-secret=f2fbf589ce5d8d3fa5c7ad0fd6721c80508464ec
spring.security.oauth2.client.registration.github.scope=read:user,user:email

jwt.secret=ThisIsMyVerySecretKeyForJwtGeneration123456789
jwt.expiration=86400000